Home-Work-3
ENFSIN/- pull request #5
Opened 2024-06-16 10:15 UTC by ENFSIN

2024-06-16 10:17 UTC, VChurekov requested changes
А где файлы cproj и sln?

2024-06-16 10:20 UTC, VChurekov requested changes

2024-06-16 10:20 UTC, VChurekov commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Введите второй число; ");
второЕ.

2024-06-16 10:20 UTC, VChurekov commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("введите число");
С большой буквы.

2024-06-16 10:20 UTC, VChurekov commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Введите второй число; ");
Тут надо наверное : а не ;

2024-06-16 10:20 UTC, VChurekov commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Введите третье число;");
Тут надо наверное : а не ;

2024-06-16 10:20 UTC, VChurekov commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Сумма=" + e);
Поиспользуй интерполяцию строки.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2024-06-16 10:37 UTC, ENFSIN commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("введите число");
Исправил.

2024-06-16 10:37 UTC, ENFSIN commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Введите второй число; ");
Исправил.

2024-06-16 10:38 UTC, ENFSIN commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Введите второй число; ");
Исправил.

2024-06-16 10:38 UTC, ENFSIN commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Введите третье число;");
Исправил.

2024-06-16 19:33 UTC, VChurekov commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Сумма=" + e);
Подсказка: вместо "Сумма=" + e, надо написать $"Сумма={e}"

2024-06-17 03:56 UTC, ENFSIN commented on Projects/Home-Work-3/ConsoleApp1/Program.cs
> +            Console.WriteLine("Сумма=" + e);
Исправил.

2024-06-18 19:15 UTC, VChurekov approved these changes

2024-06-18 19:16 UTC, merged