Calc
ENFSIN/- pull request #7
Opened 2024-06-27 05:10 UTC by ENFSIN

2024-06-27 06:48 UTC, VChurekov requested changes

2024-06-27 06:48 UTC, VChurekov commented on Projects/Switch/Program.cs
> +                string action;
Эти переменные можно объявить в том месте где они начинают использоваться.
Например: double firstValue = double.Parse(Console.ReadLine()); в строке чуть ниже

2024-06-27 06:48 UTC, VChurekov commented on Projects/Switch/Program.cs
> +                            Console.WriteLine(0);
При делении на ноль, получаем не ноль :)
Тут надо вывести либо слово бесконечность, либо что результат не определен.
Или так и сказать, что произошла ошибка: делание на ноль.

2024-06-27 06:48 UTC, VChurekov commented on Projects/Switch/Program.cs
> +                        Console.WriteLine("Не верное действие.");
Мне кажется в таком случае не стоит судить что верно, а что нет. Да и вводили мы операцию, а тут говорим про действие.
Обычно выводят что "Операция {action} неизвестна".

2024-06-27 09:19 UTC, ENFSIN commented on Projects/Switch/Program.cs
> +                string action;
Исправил.

2024-06-27 09:20 UTC, ENFSIN commented on Projects/Switch/Program.cs
> +                            Console.WriteLine(0);
Исправил.

2024-06-27 09:21 UTC, ENFSIN commented on Projects/Switch/Program.cs
> +                        Console.WriteLine("Не верное действие.");
Исправи.

2024-06-29 10:10 UTC, VChurekov approved these changes

2024-06-29 10:12 UTC, merged